language: generic

python:
  - 3.9

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

os: linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-9
      - openmpi-bin
      - libopenmpi-dev
      - binutils
      - python-pip
      - cmake
      - cmake-data

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-9
  - cmake --version
  - ln -fs /usr/bin/gfortran-9 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-9
  - ln -fs /usr/bin/gcov-9 "$HOME/.local/bin/gcov" && gcov --version
  - pip --version
  - python --version
  - pip install --user --upgrade FoBiS.py
  - source ./config/install_flap.sh
  - source ./config/install_mt_stream.sh

script:
    - ls "$MT_STREAM_GCC"
    - mkdir build && cd build && cmake .. && make && make install
