#!/bin/tcsh
#MSUB -l walltime=16:00:00
#MSUB -l nodes=4:ppn=16
#MSUB -N Rogers
#MSUB -j oe
#MSUB -o outfile
#MSUB -m abe


# Now run the script as this group - so all data files will belong

#  Shell commands
date
echo '*** Staring Parallel Job ***'
source module_intel_lanl.sh
./diffusion.sh

# restart restart0/restart
date
echo '*** All Done ***'

# 
