#!/bin/tcsh
#SBATCH --qos=standby
#SBATCH --time=16:00:00
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=36
#SBATCH --jobname Rogers
#SBATCH --output slurm%j.out
#SBATCH --error slurm%j.err
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=xiaocanli@lanl.gov
##SBATCH -A account_name     # slurm account 

# Now run the script as this group - so all data files will belong

#  Shell commands
date
echo '*** Staring Parallel Job ***'
source module_lanl_grizzly.sh
./diffusion1.sh

# restart restart0/restart
date
echo '*** All Done ***'

# 
