#!/bin/tcsh
#SBATCH --qos=standard
#SBATCH --time=8:00:00
#SBATCH --nodes=2
##SBATCH --ntasks-per-node=36
#SBATCH --job-name Rogers
#SBATCH --output slurm%j.out
#SBATCH --error slurm%j.err
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=xiaocanli@lanl.gov
##SBATCH -A account_name     # slurm account 

# Now run the script as this group - so all data files will belong

#  Shell commands
date
echo '*** Staring Parallel Job ***'
module load intel openmpi

# ./diffusion21.sh
# ./diffusion22.sh &
# ./diffusion23.sh &
# ./diffusion24.sh &
# ./diffusion25.sh &
# ./diffusion26.sh &
# ./diffusion27.sh &
# ./diffusion28.sh &
# ./diffusion29.sh &
# ./diffusion11.sh &
# ./diffusion12.sh &
# ./diffusion13.sh &
# ./diffusion14.sh &
# wait
./diffusion38.sh

# restart restart0/restart
date
echo '*** All Done ***'

# 
